name: PR Contract Comment

on:
  pull_request_target:
    types: [opened]

jobs:
  env:
    MESSAGE: |
      Two pull request approvals are required to merge outside of review meetings. If in a
      review meeting, add the `approved-in-meeting` label to this PR to merge with only
      one review. The label will be automatically removed if new commits are added to this PR.'
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE
            });
