name: Review Enforcement

on:
  pull_request:
    types: [opened, closed, synchronize, labeled, unlabeled]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  comment:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    env:
      MESSAGE: >
        Two pull request approvals are required to merge outside of review meetings. To bypass this
        requirement and merge with only one approval, add the `approved-in-meeting` label to this PR.
        The label will be automatically removed if new commits are added to this PR.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE
            });

  remove-label:
    if: (github.event_name == 'pull_request' && (github.event.action == 'synchronize' || github.event.action == 'closed'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - id: approved-in-meeting
        uses: actions/labeler@v5
        with:
          sync-labels: true

