name: Remove cr meeting label from pull requests

on:
  pull_request:
    types: [closed, synchronized]
  pull_request_review:
    types: [dismissed]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - id: approved-in-meeting
        uses: actions/labeler@v5
        with:
          sync-labels: true

